spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: article-service
          uri: lb://article
          predicates:
            - Path=/api/v1/articles/**
        - id: category-service
          uri: lb://category
          predicates:
            - Path=/api/v1/categories/**
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
