server:
  port: 8091
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: article
          uri: lb://localhost:8086
          predicates:
            - Path:/api/v1/articles/**
        - id: user
          uri: lb://localhost:8080
          predicates:
            - Path:/api/v1/users/**
        - id: category
          uri: lb://localhost:8087
          predicates:
            - Path:/api/v1/categories/**