spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: article-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/articles/**
        - id: category-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/categories/**
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/users/**
    discovery:
      enabled: true
    config:
      uri: http://localhost:8091
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
