server:
  port: 8086

spring:
  application:
    name: article
  datasource:
    url: jdbc:postgresql://localhost:5432/article
    username: mike
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  config:
    import: file:classpath:openai.properties

file:
  upload-dir: static/images/user-images

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
