server:
  port: 8091

spring:
  application:
    name: authentication
  datasource:
    url: jdbc:postgresql://localhost:5432/app_user
    username: mike
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/