server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/user
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
      show-sql: true